require File.dirname(__FILE__) + '/test_helper.rb'

context "apimodel marshalling" do
  
  setup do 
    Person.restful_publish(:name, :current_location, :pets, :sex)
    Pet.restful_publish(:name)
    Wallet.restful_publish(:contents)
    
    @person = Person.create(:name => "Joe Bloggs", :current_location => "Under a tree")
    @pet = @person.pets.create(:species => "cat", :age => 200, :name => "mietze")
    @wallet = @person.wallet = Wallet.new(:contents => "an old photo, 5 euros in coins")
    @person.save
  end
  
  teardown do
    reset_config
  end

  xspecify "should be able to handle relations that are nil/null" do
    @person.sex = nil
    @person.save!
    @person.reload

    assert_nothing_raised do
      @person.to_restful
    end

  end

  xspecify "should be able to expand a :belongs_to relationship" do
    actual = @pet.to_restful(:person).serialize_to(:xml)

    expected = <<EXPECTED
<?xml version="1.0" encoding="UTF-8"?>
<pet>
  <restful-url type="link">http://example.com:3000/pets/#{ @pet.id }</restful-url>
  <person>
    <restful-url type="link">http://example.com:3000/people/#{ @person.id }</restful-url>
    <name>Joe Bloggs</name>
    <current-location>Under a tree</current-location>
    <sex>
      <restful-url type="link">http://example.com:3000/sexes/#{ @sex.id }</restful-url>
      <sex>male</sex>
    </sex>
    <pets type="array">
      <pet>
        <restful-url type="link">http://example.com:3000/pets/#{ @pet.id }</restful-url>
        <name nil="true"></name>
      </pet>
    </pets>
  </person>
</pet>
EXPECTED

    xml_should_be_same(expected, actual)
  end

  xspecify "should be able to export content generated by methods" do
    actual = @sex.to_restful(:foo).serialize_to(:xml)

    expected = <<EXPECTED
<?xml version="1.0" encoding="UTF-8"?>
<sex>
  <restful-url type="link">http://example.com:3000/sexes/3</restful-url>
  <foo>bar</foo>
</sex>
EXPECTED

    xml_should_be_same(expected, actual)
  end

  specify "should be able to export content generated by methods (not attributes) and compute the correct style" do
    actual = @person.to_restful(:oldest_pet).serialize_to(:xml)
    oldest = @person.oldest_pet
    
    expected = <<EXPECTED
<?xml version="1.0" encoding="UTF-8"?>
<person>
  <restful-url type="link">http://example.com:3000/people/#{ @person.id }</restful-url>
  <oldest_pet>
    <restful-url type="link">http://example.com:3000/pets/#{ oldest.id }</restful-url>
    <name>#{ oldest.name }</name>
  </pet>
</person>
EXPECTED

    xml_should_be_same(expected, actual)
  end

  xspecify "should create element with nil='true' attribute if no relation is set" do 
    @person.haircut = nil
    @person.save

    actual = @person.to_restful(:haircut).serialize_to(:xml)
    expected = <<EXPECTED
<?xml version="1.0" encoding="UTF-8"?>
<person>
  <restful-url type="link">http://example.com:3000/people/#{ @person.id }</restful-url>
  <haircut nil="true"></haircut>
</person>
EXPECTED

    xml_should_be_same(expected, actual)
  end
  
  xspecify "serialize to xml, rails style" do
    actual = @person.to_restful.serialize_to(:xml)
    
    expected = <<EXPECTED
<?xml version="1.0" encoding="UTF-8"?>
<person>
  <restful-url type="link">http://example.com:3000/people/#{ @person.id }</restful-url>
  <name>Joe Bloggs</name>
  <current-location>Under a tree</current-location>
  <sex>
    <restful-url type="link">http://example.com:3000/sexes/#{ @sex.id }</restful-url>
    <sex>male</sex>
  </sex>
  <pets type="array">
    <pet>
      <restful-url type="link">http://example.com:3000/pets/#{ @pet.id }</restful-url>
      <name nil="true"></name>
    </pet>
  </pets>
</person>
EXPECTED
    xml_should_be_same(expected, actual)
  end
  
  xspecify "serialize to xml, atom style" do
    actual = @person.to_restful.serialize_to(:atom_like)
    
    expected = <<EXPECTED    
<?xml version="1.0" encoding="UTF-8"?>
<person xml:base="http://example.com:3000">
  <link rel="self" href="/people/#{ @person.id }"/>
  <name>Joe Bloggs</name>
  <current-location>Under a tree</current-location>
  <sex>
    <link rel="self" href="/sexes/#{ @sex.id }"/>
    <sex>male</sex>
  </sex>
  <pets>
    <pet>
      <link rel="self" href="/pets/#{ @pet.id }"/>
      <name></name>
    </pet>
  </pets>
</person>
EXPECTED

    xml_should_be_same(expected, actual)
  end
  
  xspecify "deserialize from rails style xml" do
    restful = @person.to_restful
    expected = restful.serialize_to(:xml)
    serializer = Restful::Serializers::XMLSerializer.new
    resource = serializer.deserialize(expected)    
    actual = serializer.serialize(resource)
    
    xml_should_be_same(expected, actual)
  end
  
  xspecify "serialize to an ar params hash" do
    
    input = <<EXPECTED
<?xml version="1.0" encoding="UTF-8"?>
<pet>
  <person-restful-url type="link">http://example.com:3000/people/#{ @person.id }</person-restful-url>
  <species>123</species>
  <name>Gracie</name>
</pet>
EXPECTED

    params = Restful.from_xml(input).serialize_to(:params)
    clone = Pet.create!(params)
    
    clone.name.should.== "Gracie"
    clone.species.should.== 123
    clone.person_id.should.== @person.id
  end
  
  xspecify "deserialize from atom style xml" do
    restful = @pet.to_restful
    expected = restful.serialize_to(:atom_like)
    serializer = Restful::Serializers::AtomLikeSerializer.new
    resource = serializer.deserialize(expected)
    actual = serializer.serialize(resource)
    
    xml_should_be_same(expected, actual)
  end

  xspecify "serialize to params" do
    actual = @person.to_restful.serialize_to(:params)
    
    expected = 
      {
        :name => "Joe Bloggs",
        :current_location => "Under a tree",
        :sex_attributes => {
          :sex => "male"
        },
        :pets_attributes => [ {:name => nil} ]
      }

    actual.should.== expected
  end

  xspecify "deserialize from params" do
    restful = @person.to_restful
    expected = restful.serialize_to(:params)
    serializer = Restful::Serializers::ParamsSerializer.new
    resource = serializer.deserialize(expected)
    actual = Person.create(expected).to_restful.serialize_to(:params)
    
    actual.should.== expected
  end
end
